- name: Ensure necessary packages are installed.
  become: yes
  pacman:
    name:
      - aspell
      - aspell-de
      - aspell-en
      - base
      - base-devel
      - bind
      - bluez
      - bluez-tools
      - bluez-utils
      - bob
      - bridge-utils
      - brightnessctl
      - cifs-utils
      - clang
      - clinfo
      - cloc
      - ctags
      - cups
      - ffmpeg
      - firefox
      - foot
      - fprintd
      - fwupd
      - fzf
      - gammastep
      - gnu-free-fonts
      - grim
      - gromit-mpx
      - grub
      - hplip
      - imagemagick
      - img2pdf
      - imv
      - jq
      - kanshi
      - lf
      - libqalculate
      - linux
      - linux-firmware
      - mako
      - man-db
      - man-pages
      - minicom
      - mpc
      - mpd
      - mpv
      - networkmanager
      - nmap
      - openresolv
      - openssh
      - pass
      - pavucontrol
      - pdftk
      - pipewire-pulse
      - pulsemixer
      - qemu-full
      - rsync
      - scrcpy
      - slurp
      - sof-firmware
      - stow
      - sway
      - swayidle
      - swaylock
      - syncthing
      - thunderbird
      - tipp10
      - tmux
      - translate-shell
      - tree
      - ttf-inconsolata
      - ufw
      - unzip
      - vis
      - w3m
      - wev
      - wf-recorder
      - wireguard-tools
      - wireplumber
      - wl-clipboard
      - wl-mirror
      - wlr-randr
      - wmenu
      - xdg-desktop-portal-gtk
      - xdg-user-dirs
      - xorg-xwayland
      - zathura
      - zathura-pdf-mupdf
      - zathura-ps
      - zip
      - zsh
    state: present

